número=int(input('Digite um número de 0 a 9999: '))
n=str(número)
print('Unidade: {}'.format(n[3]))
print('Dezena: {}'.format(n[2]))
print('Centena: {}'.format(n[1]))
print('Milha75r: {}'.format(n[0]))